# Generated by Django 2.0.4 on 2018-05-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='description',
            new_name='time',
        ),
    ]
